# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  VERSION: '$(build.buildNumber)'
  DOCKER_REGISTRY: $(dockerId).azurecr.io

steps:
- script: sudo service docker status
  displayName: 'docker status'

- script: docker-compose -f docker-compose.yml -f docker-compose.override.yml build
  displayName: 'docker-compose build'

- script: |
    echo "$(dockerPassword)" | docker login  $(dockerId).azurecr.io -u $(dockerUsername) --password-stdin
    docker push $(dockerId).azurecr.io/aks-web:$(VERSION)    
  displayName: "docker publish"
  
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/Kube/
    contents: '**/*.*'
    targetFolder: $(Build.ArtifactStagingDirectory)/Kube/
    
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactsName: 'drop'