apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: kube-system
  name: aminbs23-eastus2-cloudapp-azure-com-cert-staging
spec:
  secretName: aminbs23-eastus2-cloudapp-azure-com-staging
  dnsNames:
  - aminbs23.eastus2.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - aminbs23.eastus2.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer  