apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: app-dev
  name: aksexam-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aksexam
      app.kubernetes.io/instance: app-dev
      app.kubernetes.io/part-of: aks-services
      app.kubernetes.io/managed-by: azure-devops
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aksexam
        app.kubernetes.io/instance: app-dev
        app.kubernetes.io/version: "#{Release.Artifacts.AksExam.BuildNumber}#"
        app.kubernetes.io/part-of: aks-services
        app.kubernetes.io/managed-by: azure-devops
    spec:
      containers:
        - name: aksexam
          image: faisalacr.azurecr.io/aksexam:#{Release.Artifacts.AksExam.BuildNumber}#
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  namespace: app-dev
  name: aksexam-service
  labels:
    app.kubernetes.io/name: aksexam
    app.kubernetes.io/instance: app-dev
    app.kubernetes.io/version: "#{Release.Artifacts.AksExam.BuildNumber}#"
    app.kubernetes.io/part-of: aks-services
    app.kubernetes.io/managed-by: azure-devops
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
  selector:
    app.kubernetes.io/name: aksexam
    app.kubernetes.io/instance: app-dev
    app.kubernetes.io/version: "#{Release.Artifacts.AksExam.BuildNumber}#"
    app.kubernetes.io/part-of: aks-services
    app.kubernetes.io/managed-by: azure-devops
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: app-dev
  name: aksexam-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/server-snippets: "gzip on;"
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  # tls:
    # - hosts:
        # - aminbs23.eastus.cloudapp.azure.com
      # secretName: aminbs23-eastus-cloudapp-azure-com-staging
  rules:
    - host: aminbs23.eastus2.cloudapp.azure.com
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: aksexam-service
              servicePort: 80
